### ISSUE TITLE
Live streaming - Buffering

### ISSUE THREAD

**Issue by milodude** [mojtabaghiasi/video_js#2]
I was wondering how can I set the buffer up for a live stream. For example having an hour buffer where I can scroll up and down through the stream in order to go backa bit if I need to review a certain moment of the stream. Is this possible? Also the control is being hidden from me and just says "live". Is there any way  to show the control and set the buffer properly?

![image](https://user-images.githubusercontent.com/4110660/145599617-06fbd7a5-e6e3-4a05-bf16-02d70975421d.png)

**Comment by mojtabaghiasi** [comment]
If you set the controls option to true in videoJsOptions for VideoJsController, you will have your video controllers like play pause and video seek bar, so you will see your video buffer.
